<?php
App::uses('AppController', 'Controller');
/**
 * Graphics Controller
 *
 * @property Graphic $Graphic
 */
class GraphicsController extends AppController {
	
	public function beforeFilter() {
		parent::beforeFilter();
		$this->Auth->deny();	
	}
	
	
/* Not in use, generated by bake 
	public function index() {
		$this->Graphic->recursive = 0;
		$this->set('graphics', $this->paginate());
	}

	public function view($id = null) {
		$this->Graphic->id = $id;
		if (!$this->Graphic->exists()) {
			throw new NotFoundException(__('Invalid graphic'));
		}
		$this->set('graphic', $this->Graphic->read(null, $id));
	}

	public function add() {
		if ($this->request->is('post')) {
			$this->Graphic->create();
			if ($this->Graphic->save($this->request->data)) {
				$this->Flash->set(__('The graphic has been saved'));
				$this->redirect(array('action' => 'index'));
			} else {
				$this->Flash->set(__('The graphic could not be saved. Please, try again.'));
			}
		}
		$releases = $this->Graphic->Release->find('list');
		$this->set(compact('releases'));
	}

	public function edit($id = null) {
		$this->Graphic->id = $id;
		if (!$this->Graphic->exists()) {
			throw new NotFoundException(__('Invalid graphic'));
		}
		if ($this->request->is('post') || $this->request->is('put')) {
			if ($this->Graphic->save($this->request->data)) {
				$this->Flash->set(__('The graphic has been saved'));
				$this->redirect(array('action' => 'index'));
			} else {
				$this->Flash->set(__('The graphic could not be saved. Please, try again.'));
			}
		} else {
			$this->request->data = $this->Graphic->read(null, $id);
		}
		$releases = $this->Graphic->Release->find('list');
		$this->set(compact('releases'));
	}

	public function delete($id = null) {
		if (!$this->request->is('post')) {
			throw new MethodNotAllowedException();
		}
		$this->Graphic->id = $id;
		if (!$this->Graphic->exists()) {
			throw new NotFoundException(__('Invalid graphic'));
		}
		if ($this->Graphic->delete()) {
			$this->Flash->set(__('Graphic deleted'));
			$this->redirect(array('action' => 'index'));
		}
		$this->Flash->set(__('Graphic was not deleted'));
		$this->redirect(array('action' => 'index'));
	}
*/
}
